src/Gladtur/TagBundle/Entity/TvguserProfile.php
<?php
namespace Gladtur\TagBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="Gladtur\TagBundle\Entity\TvguserProfileRepository")
 * @ORM\Table(name="tvguser_profile")
 */
class TvguserProfile
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\ManyToMany(targetEntity="Tag", inversedBy="profiles")
     */
    private $tags;

    /**
     * @ORM\OneToOne(targetEntity="UserProfileByTags", mappedBy="userProfile")
     */
    protected $freeProfile;

    /**
     * @ORM\Column(name="individualized", type="boolean", nullable=false)
     */
    protected $individualized;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $webiconpath;

    /**
     * @param mixed $webiconpath
     */
    public function setWebiconpath($webiconpath)
    {
        $this->webiconpath = $webiconpath;
    }

    /**
     * @return mixed
     */
    public function getWebiconpath()
    {
        return $this->webiconpath;
    }

    /**
     * @var integer $user
     * @ORM\OneToMany(targetEntity="UserLocationTagData", mappedBy="user_profile")
     */
    private $userLocationTagData;
    /**
     *
     * @ORM\OneToMany(targetEntity="User", mappedBy="profile")
     */
    protected $user;

    /**
     * @ORM\OneToMany(targetEntity="UserLocationComments", mappedBy="profile")
     */
    private $user_location_comments;

    /**
     * @ORM\OneToMany(targetEntity="UserLocationData", mappedBy="profile")
     */
    private $user_location_data;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $rank;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $txt_description;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
    }

    /**
     * @var string $readableName
     *
     * @ORM\Column(name="readable_name", type="string", length=255, nullable=true)
     */
    private $readableName;

    public function getFullName()
    {
        return $this->getReadableName();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @Assert\File(maxSize="5M")
     */
    private $avatar;

    /**
     * @Assert\File(maxSize="5M")
     */
    private $webavatar;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $path;

    public function addTags(\Gladtur\TagBundle\Entity\Tag $tags)
    {
        $this->tags[] = $tags;

        return $this;
    }

    public function removeTags(\Gladtur\TagBundle\Entity\Tag $tag)
    {
        $this->tags->removeElement($tag);
    }

    public function getTags($locationCategoryId = null)
    {
        if (!$locationCategoryId) {
            return $this->tags;
        } else {
            $categoryTags = new ArrayCollection();
            foreach ($this->tags as $tag) {
                $locationCategoryIds = array();
                foreach ($tag->getLocationCategories() as $tagLocationCategory) {
                    $locationCategoryIds[] = $tagLocationCategory->getId();
                }
                if (in_array($locationCategoryId, $locationCategoryIds)) {
                    $categoryTags->add($tag);
                }
            }
        }

        return $categoryTags;
    }


    public function getReadableName()
    {
        return $this->readableName;
    }

    public function setReadableName($readableName)
    {
        $this->readableName = $readableName;

        return $this;
    }

    /**
     * Get avatar.
     *
     * @return UploadedFile
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     * Sets avatar.
     *
     * @param UploadedFile $avatar
     */
    public function setAvatar(UploadedFile $avatar = null)
    {
        $this->avatar = $avatar;
    }

    /**
     * @param UploadedFile $webavatar
     */
    public function setWebavatar(UploadedFile $webavatar = null)
    {
        $this->webavatar = $webavatar;
    }

    /**
     * @return UploadedFile
     */
    public function getWebavatar()
    {
        return $this->webavatar;
    }


    public function getAbsolutePath()
    {
        return null === $this->path
            ? null
            : $this->getUploadRootDir() . '/' . $this->path;
    }

    /** Gets the path for the App-icon for use in Form Builders **/
    public function getWebPath()
    {
        return null === $this->path
            ? null
            : $this->getUploadDir() . '/' . $this->path;
    }

    /** Gets the path for the Website-icon for use in Form Builders **/
    public function getWebPathSite()
    {
        return null === $this->webiconpath
            ? null
            : $this->getUploadDir() . '/website/' . $this->webiconpath;
    }

    protected function getUploadRootDir()
    {
        // the absolute directory path where uploaded
        // documents should be saved
        return __DIR__ . '/../../../../web/' . $this->getUploadDir();
    }

    protected function getUploadDir()
    {
        // get rid of the __DIR__ so it doesn't screw up
        // when displaying uploaded doc/image in the view.
        return 'uploads/icons/profiles';
    }

    public function upload($profileForm, $fieldname = null)
    {
        if (!$fieldname) {
            return;
        } // Nofilefield used asa source
        /*
     *
            // the file property can be empty if the field is not required
            if (null === $this->getAvatar()) {
                return;
            }
    */
        // use the original file name here but you should
        // sanitize it at least to avoid any security issues

        // move takes the target directory and then the
        // target filename to move to
        $ulRootDir = $this->getUploadRootDir();
        if ($fieldname == 'webavatar') {
            $ulRootDir = $this->getUploadRootDir() . '/website';
        }
        if ($profileForm[$fieldname]->getData()) {
            $avalancheDir = str_replace('/web/uploads/', '/web/uploads/avalanche/thumbnail/', $ulRootDir);
            if (file_exists($avalancheDir . '/' . $profileForm[$fieldname]->getData()->getClientOriginalName())) {
                unlink($avalancheDir . '/' . $profileForm[$fieldname]->getData()->getClientOriginalName());
            }
            $profileForm[$fieldname]->getData()->move(
            // $this->getAvatar()->move(
                $ulRootDir,
                $profileForm[$fieldname]->getData()->getClientOriginalName()
            );
            if ($fieldname == 'webavatar') {
                // Icon path for the website icon
                $this->webiconpath = $profileForm[$fieldname]->getData()->getClientOriginalName();
            } else {
                // Icon path for the App icon
                $this->path = $profileForm[$fieldname]->getData()->getClientOriginalName();
            }

            // clean up the file property as you won't need it anymore
            // $this->avatar = null;
        }
    }

    public function asJSON()
    {
        return array($this->getId(), $this->getReadableName());
    }

    public function __toString()
    {
        return $this->getReadableName();
    }

    /**
     * @param mixed $rank
     */
    public function setRank($rank)
    {
        $this->rank = $rank;
    }

    /**
     * @return mixed
     */
    public function getRank()
    {
        return $this->rank;
    }

    /**
     * @param mixed $txt_description
     */
    public function setTxtDescription($txt_description)
    {
        $this->txt_description = $txt_description;
    }

    /**
     * @return mixed
     */
    public function getTxtDescription()
    {
        return $this->txt_description;
    }

    /**
     * @ORM\OneToMany(targetEntity="ReportedItem", mappedBy="user_profile")
     */
    private $report_items;

    public function getPath()
    {
        return $this->path;
    }

    /**
     * @param bool $individualized
     */
    public function setIndividualized($individualized)
    {
        $this->individualized = $individualized;
    }

    /**
     * @return bool
     */
    public function getIndividualized()
    {
        return $this->individualized;
    }

}

src/Gladtur/TagBundle/Controller/UserLocationDataController.php
<?php
namespace Gladtur\TagBundle\Controller;

use Gladtur\TagBundle\Entity\UserLocationMedia;
use Gladtur\TagBundle\Form\UserLocationDataType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Gladtur\TagBundle\Entity\Location;
use Gladtur\TagBundle\Form\LocationType;
use JMS\Serializer;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
/**
 * Created by JetBrains PhpStorm.
 * User: mortenthorpe
 * Date: 1/13/13
 * Time: 4:10 PM
 * To change this template use File | Settings | File Templates.
 */
/**
 * UserLocationData controller.
 *
 * @Route("location_user_data")
 */
class UserLocationDataController extends Controller
{

    public function __construct()
    {
        //parent::setContainer(new ContainerInterface());
        $this->container = new \Symfony\Component\DependencyInjection\Container();
        // ... deal with any more arguments etc here
    }

    // \@Route("/{id}/{lang}/{file}", requirements={"id" = "\d+"}, defaults={"file" = null})
    /**
     * Lists all UserLocationData entities.
     *
     * @Route("", name="location_user_data", defaults={"orderDir" = 1})
     * @Template()
     */
    public function indexAction($orderDir)
    {
        $menuItems = array('tagIndex' => '@tag', 'location_tagIndex' => '@location_tag', 'locationIndex' =>'@location', 'tag_categoryIndex' => '@tagcategoryIndex' );
        // See: http://stackoverflow.com/questions/12017254/symfony2-how-to-join-on-many-to-many-relations-using-querybuilder //
        $em = $this->getDoctrine()->getManager();
        $entities = $em->getRepository('GladturTagBundle:UserLocationData');//->findAll();
        $orderDir=($orderDir==1)?'desc':'asc';
        $query=$entities->createQueryBuilder('user_data')->where('user_data.user='.$this->getUser()->getId())->orderBy('user_data.id',$orderDir)->setMaxResults(1);
        //if($location)$query=$query->where('user_data.location='.$location);
        $query=$query->getQuery();//where('user_data.locationId=')->getQuery();
        $entities=$query->getResult();
        return array(
            'entities' => $entities,
            'menuItems' => $menuItems
        );
    }

    /**
     * Finds and displays a UserLocationData entity.
     *
     * @Route("/{id}/show", name="location_user_data_show")
     * @Template()
     */
    public function showAction($id){

        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('GladturTagBundle:UserLocationData')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find UserLocationData entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Finds and displays a UserLocationData entity.
     *
     * @Route("/json/{id}/show", name="location_user_data_json_show")
     * @Template()
     */
    public function showJSONAction($id){
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('GladturTagBundle:UserLocationData')->createQueryBuilder('data')->select('data.id', 'data.txt_description')->getQuery()->getResult();//   find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find UserLocationData entity.');
        }

        $deleteForm = $this->createDeleteForm($id);
        $serializer = $this->container->get('jms_serializer');
        $response=new \Symfony\Component\HttpFoundation\Response($serializer->serialize($entity, 'json'));
        $response->headers->set('Content-Type', 'application/json');
        return $response;

    }
    /* Copy-pasted, auto-edited */
    /**
     * Displays a form to create a new Location entity.
     *
     * @Route("/new", name="location_user_data_new")
     * @Template()
     */
    public function newAction()
    {
        $entity = new Location();
        $form   = $this->createForm(new LocationType(), $entity);

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Creates a new Location entity.
     *
     * @Route("/create", name="location_user_data_create")

     * @Template("/GladturTagBundle:UserLocationData:new.html.twig")
     */
    public function createAction(Request $request)
    {
        $entity  = new Location();
        $form = $this->createForm(new LocationType(), $entity);
        $form->bind($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('location_user_data_show', array('id' => $entity->getId())));
        }

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Displays a form to edit an existing Location entity.
     *
     * @Route("/{id}/edit", name="location_user_data_edit")
     * @Template()
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();
        $entity = $em->getRepository('GladturTagBundle:UserLocationData')->find($id);

  /*      $dQuery=$em->createQuery("select d from Gladtur\TagBundle\Entity\UserLocationData d, Gladtur\TagBundle\Entity\User u where u.profile=" . $cur_usr->getProfile()->getId(). " and d.location=".$id." order by d.created_at desc")->setMaxResults(1); -- Fetches UserLocationData results ALSO dependent on user profile! */

        //$entity = $em->getRepository('GladturTagBundle:UserLocationData')->createQueryBuilder('LocationUserDatas')->where('LocationUserDatas.location='.$entity->getId())->orderBy('LocationUserDatas.id', 'desc')->getQuery()->getResult();
      //  $entityUserTagData = $em->getRepository('GladturTagBundle:UserLocationTagData')->createQueryBuilder('LocationUserTagDatas')->where('LocationUserTagDatas.location='.$entity->getLocation()->getId())/*->orderBy('LocationUserTagDatas.user', 'desc')*/->getQuery()->getResult();
        /* http://docs.doctrine-project.org/en/2.0.x/reference/query-builder.html
        // Example - $qb->leftJoin('u.Phonenumbers', 'p', Expr\Join::WITH, $qb->expr()->eq('p.area_code', 55))
        */
        //      $entityUserCategories = $em->getRepository('GladturTagBundle:UserLocationDataCategory')->createQueryBuilder('LocationCategory')->leftJoin('UserLocationData')->where('LocationCategory.')

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Location entity.');
        }


        $entity->addMedia(new UserLocationMedia());
        $editForm = $this->createForm(new UserLocationDataType(), $entity);
        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'userLocationTagData' => array(),
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Edits an existing Location entity.
     *
     * @Route("/{id}/update", name="location_user_data_update")

     * @Template("/GladturTagBundle:UserLocationData:edit.html.twig")
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('GladturTagBundle:UserLocationData')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Location entity.');
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createForm(new LocationType(), $entity);
        $editForm->bind($request);

        if ($editForm->isValid()) {
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('location_user_data_edit', array('id' => $id)));
        }

        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Deletes a Location entity.
     *
     * @Route("/{id}/delete", name="location_user_data_delete")
     */
    public function deleteAction($id)
    {
        $em = $this->getDoctrine()->getManager();
        $entity = $em->getRepository('GladturTagBundle:UserLocationData')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Location entity.');
        }

        $em->remove($entity);
        $em->flush();

        return $this->redirect($this->generateUrl('location'));
    }

    private function createDeleteForm($id)
    {
        return $this->createFormBuilder(array('id' => $id))
            ->add('id', 'hidden')
            ->getForm()
            ;
    }
}

src/Gladtur/TagBundle/Resources/views/UserLocationData/edit.html.twig
{% extends "GladturTagBundle::layout.html.twig" %}
{% block content %}
<div class="main_left" style="float:left;width:580px;margin-right:45px">
<h1>Location edit</h1>
<form action="{{ path('location_user_data_update', { 'id': entity.id }) }}" method="post" {{ form_enctype(edit_form) }}>
    {% for mediafield in edit_form.media %}
        {{ form_row(mediafield)  }}
    {% endfor %}
    {{ form_rest(edit_form) }}
    <p>
        <button type="submit">Edit</button>
    </p>
</form>

<ul class="record_actions">
    <li>
        <a href="{{ path('location_user_data') }}">
            Back to the list
        </a>
    </li>
    <li>
        <form action="{{ path('location_user_data_delete', { 'id': entity.id }) }}" method="post">
            {{ form_widget(delete_form) }}
            <button type="submit">Delete</button>
        </form>
    </li>
</ul>
</div>
<div class="main_right" style="float:left;width:336px">

</div>
{% endblock %}

src/Gladtur/TagBundle/Resources/views/UserLocationData/index.html.twig
<!-- UserLocationData/index.html.twig //-->
<div>
    <p>User Location Data!</p>
    {% for entity in entities %}
        {{ entity.readableName }} ({{ entity.location.id }}) - af brugeren '{{ entity.user.username }}'
        <ul>
            <li>Opens at: {{ entity.hoursOpeningtime | json_encode  }}</li>
            <li>Closes at: {{ entity.hoursClosingtime | json_encode }}</li>
        </ul>
        <div>
            <h3>Media and description of this place:</h3>
            {{ entity.media }}
            {{ entity.txtDescription }}
        </div>
    {% endfor %}
</div>
<div class="admin_actions">
    {% include "GladturTagBundle:UserLocationData:role_admin.html.twig" %}
</div>

src/Gladtur/TagBundle/Resources/views/UserLocationData/new.html.twig
{% extends "GladturTagBundle::layout.html.twig" %}
{% block content %}
<h1>Opret sted</h1>

<form action="{{ path('location_user_data_create') }}" method="post" {{ form_enctype(form) }}>
    {{ form_widget(form) }}
    <p>
        <button type="submit">Opret nyt sted</button>
    </p>
</form>

<ul class="record_actions">
    <li>
        <a href="{{ path('location_user_data') }}">
            Til oversigt over steder
        </a>
    </li>
</ul>
{% endblock %}

src/Gladtur/TagBundle/Resources/views/UserLocationData/order_data.html.twig
<ul>
    <li>Newest first(default)</li>
    <li>Oldest first(default)</li>
</ul>

src/Gladtur/TagBundle/Resources/views/UserLocationData/role_admin.html.twig
{% if is_granted('ROLE_ADMIN') %}
    <ul class="menu_horizontal">
    <li><a href="#">View all users data for this location</a></li>
    <li><a href="#">Edit</a></li>
    <li><a href="#">Delete</a></li>
    </ul>
{% endif %}

src/Gladtur/TagBundle/Resources/views/UserLocationData/show.html.twig
{% extends "GladturTagBundle::layout.html.twig" %}
{% block content %}
<h1>Location</h1>

<table class="record_properties">
    <tbody>
        <tr>
            <th>Id</th>
            <td>{{ entity.id }}</td>
        </tr>
    </tbody>
</table>

<ul class="record_actions">
    <li>
        <a href="{{ path('location') }}">
            Back to the list
        </a>
    </li>
    <li>
        <a href="{{ path('location_edit', { 'id': entity.id }) }}">
            Edit
        </a>
    </li>
    <li>
        <form action="{{ path('location_delete', { 'id': entity.id }) }}" method="post">
            {{ form_widget(delete_form) }}
            <button type="submit">Delete</button>
        </form>
    </li>
</ul>
{% endblock %}

src/Gladtur/TagBundle/Resources/views/UserLocationData/sidebar.html.twig
<div id="user_data_sidebar">
    {% if locationData %}
    <h3>Beskrevet af brugerne</h3>
    {% else %}
    <h3 class="notice">&quot;{{ location.readableName }}&quot; er endnu ikke beskrevet af nogle brugere!</h3>
    {% endif %}
{% if locationData | length > 0 %}
<ul id="user_data_list">
        {% for user_data in locationData %}
            {%  if (user_data.user and not user_data.isEmptyRecord()) %}
            <li>{{ user_data.user }} ({{ user_data.profile }})
                <ul class="user_data" style="display:none">
                    {% if user_data.phone %}
                    <li>Telefon: {{ user_data.phone }}</li>
                    {% endif %}
                    {% if user_data.mail %}
                    <li>E-mail: {{ user_data.mail }}</li>
                    {% endif %}
                    {% if user_data.contactPerson %}
                    <li>Kontakt-person: {{ user_data.contactPerson }}
                    {% endif %}
                    {% if user_data.txtDescription %}
                    <li>Beskrivelse:<br/>{{ user_data.txtDescription }}</li>
                    {% endif %}
                </ul>
            </li>
            {%  endif %}
        {% endfor %}
</ul>
{% endif %}
</div>